# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/implementation1/gRPC/ClientProxy.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*src/implementation1/gRPC/ClientProxy.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"W\n\x0cWellnessData\x12\x0b\n\x03\x61ir\x18\x01 \x01(\x02\x12\x0b\n\x03\x63o2\x18\x02 \x01(\x02\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2T\n\x12\x43lientProxyService\x12>\n\x13SendWellnessResults\x12\r.WellnessData\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.implementation1.gRPC.ClientProxy_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WELLNESSDATA._serialized_start=108
  _WELLNESSDATA._serialized_end=195
  _CLIENTPROXYSERVICE._serialized_start=197
  _CLIENTPROXYSERVICE._serialized_end=281
# @@protoc_insertion_point(module_scope)
